### PR TITLE
Update for 1.12.2

### PR DESCRIPTION
**Pull request by Real-Gecko**
Compiled with **forge-1.12.2-14.23.2.2611-mdk** and tested with MC **1.12.2**, works like a charm. Even works alongside with __Way Stones__ mod

### CODE REVIEW

**Comment by TrinaryLogic** [comment]
Awesome thanks for this. I have had far too much on my plate lately. I'm going to merge it and test it now

**Comment by TrinaryLogic** [comment]
I'm having some problems with the mod still on this end. It compiles fine but crashes during world generation with a NoSuchMethodError. This is one of the things that stopped me releasing a 1.12 build initially. Can you let me know what forge and mod versions you are running your client with and confirm that villages are generating properly?

**Comment by Real-Gecko** [comment]
Plugin definitely works, here're screenshots of new world with seed `123`.
Generated without muon:

Now recreated with the same seed and only muon installed:

Here's the MultiMC output log with only muon installed:
[multimc-muon.log](https://github.com/MinimumContent/muon/files/1735591/multimc-muon.log)
And here's my current survival MultiMC output log, as you'll see here I have 68 more mods installed, and muon saves the day definitely:
[multimc.log](https://github.com/MinimumContent/muon/files/1735596/multimc.log)

**Comment by Real-Gecko** [comment]
BTW, I tested it both on Windows 10 and Linux.

**Comment by TrinaryLogic** [comment]
Awesome, thanks for the confirmation. I just now figured out what the problem in my build environment was. I'll be uploading the new version to curseforge shortly. Thanks very much for your effort on this!

**Comment by Real-Gecko** [comment]
Well my efforts in this were close to zero, thanks to you for this awesome plugin. Finally I have no need to unbury priests and blacksmiths in every second village I find :D

**Pull request merged**
